dist: xenial
language: python
python: 2.7
install:
- wget https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
- sudo dpkg -i vagrant_2.2.2_x86_64.deb
- pip install ansible==2.7.0
- pip install netaddr
before_script:
- vagrant plugin install vagrant-aws
- ssh-keygen -y -f ~/.vagrant.d/insecure_private_key > ~/.vagrant.d/insecure_private_key.pub
- ln -s ./ JoergFiedler.freebsd-jailed-nginx
script:
- ansible-galaxy install -p ./ -r .requirements.yml
- vagrant box add JoergFiedler/FreeBSD-11.2 --provider aws
- vagrant up nginx-proxy --provider aws
- host=$(vagrant ssh-config |grep HostName |awk '{print $2}')
- test $(curl -w %{http_code} -s -H "Host:www.freebsd.org" -o /dev/null http://${host}) == "200"
after_script:
- vagrant destroy -f
env:
  global:
